// Step 9 — the publication payload.
//
// The runner GETs this, writes the files into the public finava-live repo, and
// commits. That ordering is the integrity claim: the commit lands BEFORE the
// market opens and /api/live/execute refuses to trade anything whose content
// hash does not match a resolvable commit. Publication is not a report on what
// happened, it is a precondition of it happening.
//
// This route only reads. It deliberately writes nothing, so a failed export can
// be retried freely and cannot alter the record it is describing.

import { NextResponse } from "next/server";
import { withHarness } from "@/lib/live/harness";
import { getRunState } from "@/lib/live/runState";
import { getChainHeads, canonicalJson, hashEntry, CHAIN_GENESIS } from "@/lib/live/ledger";
import { getDecisionsForDay, getSnapshot } from "@/lib/live/ledgerRead";
import { readTranscript } from "@/lib/live/transcripts";
import { MANDATE_V1 } from "@/lib/schemas/live/snapshot";
import { executionMode } from "@/lib/live/version";
import { provenance } from "@/lib/live/promptHash";
import { scoringRegistration } from "@/lib/live/scoring";
import { scoreProvenance, summariseProvenance } from "@/lib/live/provenance";
import { apiError } from "@/lib/apiError";
import { createHash } from "node:crypto";

export const maxDuration = 300;

/** The disclaimer carried in every published day. Non-negotiable, not decorative. */
export const DISCLAIMER =
  "Finava Live is an autonomous paper-trading experiment. No real money is at " +
  "risk and no position described here is held. Nothing in this repository is " +
  "investment advice, a recommendation, or an offer to buy or sell any security. " +
  "The decisions are generated by language models and are frequently wrong; they " +
  "are published so that they can be scored, not so that they can be followed.";

export const GET = withHarness(async (req) => {
  const runId = new URL(req.url).pathname.split("/").at(-2) ?? "";
  if (!/^\d{4}-\d{2}-\d{2}$/.test(runId)) {
    return apiError("invalid_run", "runId must be an ET trading day (YYYY-MM-DD)", 400);
  }

  const [state, snapshot, decisions, heads] = await Promise.all([
    getRunState(runId),
    getSnapshot(runId),
    getDecisionsForDay(runId),
    getChainHeads(),
  ]);

  if (!state) return apiError("not_found", `No run recorded for ${runId}`, 404);

  // Transcripts are published in full, per decision. Publishing the conclusions
  // without the reasoning would make the record unfalsifiable — the dissent and
  // the discarded arguments are the parts that let a reader judge the process
  // rather than just the outcome.
  const transcripts: Record<string, string> = {};
  for (const [step, value] of Object.entries(state.steps)) {
    const r = (
      value as {
        result?: { transcript?: string; transcriptRef?: string; ticker?: string; mode?: string };
      }
    ).result;
    if (!r) continue;
    const key = r.ticker ? `${r.ticker}-${r.mode}` : step;

    // Debate transcripts live in their own documents (see transcripts.ts); a
    // step that still carries its text inline is one recorded before that move,
    // or a step small enough never to have needed it. Publish either, and say so
    // in the file when a referenced transcript cannot be resolved — a silently
    // missing transcript would make the record look thinner than it was.
    if (r.transcriptRef) {
      const id = r.transcriptRef.replace(/^liveTranscripts\//, "");
      const text = await readTranscript(id);
      transcripts[key] = text ?? `[transcript ${r.transcriptRef} could not be resolved]`;
    } else if (r.transcript) {
      transcripts[key] = r.transcript;
    }
  }

  const day = {
    tradingDay: runId,
    generatedAt: new Date().toISOString(),
    executionMode: executionMode(),
    // agentVersion + the deployed commit + the hash: the commit is what lets a
    // reader check out the exact prompts this day's decisions were made under.
    ...provenance(),
    mandate: MANDATE_V1,
    // The method this day is scored under, pinned by hash to the version
    // registered before any decision existed.
    scoring: scoringRegistration(),
    snapshot,
    decisions,
    // Entries AND rejections, counted separately and in the open — the rejected
    // cohort is the counterfactual, so burying it would defeat the measurement.
    counts: {
      entries: decisions.filter((d) => d.kind === "entry").length,
      exits: decisions.filter((d) => d.kind === "exit").length,
      rejects: decisions.filter((d) => d.kind === "reject").length,
      blindReunderwrites: decisions.filter((d) => d.blindReunderwrite).length,
    },
    // How much of the day's evidence could actually be dated.
    //
    // Derived from the stamps already on each decision, never stored: a reader
    // recomputes it from these same files rather than trusting a figure only we
    // can produce. Expect "weak" to dominate today — Finnhub's fundamentals
    // carry no publication timestamp, so most facts are undated by construction,
    // and a summary that flattered that would hide the thing worth knowing.
    provenance: summariseProvenance(
      decisions.map((d) => scoreProvenance(d.evidence ?? [], d.dataGaps ?? []))
    ),
    creditsSpent: state.creditsSpent,
    chainHeads: heads.heads,
    chainGenesis: CHAIN_GENESIS,
    disclaimer: DISCLAIMER,
  };

  // The content hash the execute step checks the commit against. Computed over
  // canonical JSON so the runner's file bytes and this response agree.
  const payload = canonicalJson(day);
  const contentHash = createHash("sha256").update(payload).digest("hex");

  return NextResponse.json({
    runId,
    contentHash,
    files: {
      [`days/${runId}/day.json`]: day,
      [`days/${runId}/transcripts.json`]: transcripts,
    },
    // Recomputable by anyone from the published files — that is the point.
    verify: {
      method: "sha256(canonicalJson(payload) + prevHash), chained per collection",
      genesis: CHAIN_GENESIS,
      heads: heads.heads,
      example: hashEntry({ example: true }, CHAIN_GENESIS),
    },
  });
});
